package grafica;

import java.util.ArrayList;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;

import logica.Logica;
import valueObject.VODesgloce;

public class DesgloceDeVentas extends CustomComponent implements View {

	@AutoGenerated
	private VerticalLayout mainLayout;
	private PopupDateField date;
	private Label lblTitle;	
	private Grid grdDesgloce;
	private BeanItemContainer<VODesgloce> ds;	
	private Logica logica;
	private Label lblMessage;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DesgloceDeVentas() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		logica = new Logica();

		date.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub		
				getDesgloce();					
			}
		});
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
		mainLayout = new VerticalLayout();	
		mainLayout.setSpacing(true);		
		mainLayout.setImmediate(true);
		mainLayout.setWidth("100%");
		
		lblTitle = new Label("Desgloce de ventas");
		mainLayout.addComponent(lblTitle);
		
		date = new PopupDateField();				
		date.setCaption("Fecha");
		date.setImmediate(true);		
		mainLayout.addComponent(date);
		
		lblMessage = new Label("");
		lblMessage.setStyleName("messageAlert");
		mainLayout.addComponent(lblMessage);
		
		grdDesgloce = new Grid();		
		grdDesgloce.setSizeFull();
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		lblMessage.setValue("");
		date.setValue(new Date());		
			
		if(grdDesgloce != null){
			mainLayout.removeComponent(grdDesgloce);		
		}		
	}
	
	private void getDesgloce(){
		if(grdDesgloce != null){
			mainLayout.removeComponent(grdDesgloce);			
		}
		
		if(date.isValid()){			
			ArrayList<VODesgloce> array =  logica.DesgloceVentas(date.getValue());
			if(array != null && !array.isEmpty()){
				ds = new BeanItemContainer<VODesgloce>(VODesgloce.class, array);
				grdDesgloce.removeAllColumns();
				grdDesgloce.setContainerDataSource(ds);
				mainLayout.addComponent(grdDesgloce);	
				lblMessage.setValue("");
			}else{
				lblMessage.setValue("No hay registros para mostrar");
			}
		}		
	}

}
