package grafica;

import java.util.ArrayList;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;
import com.vaadin.data.Property.ValueChangeEvent;
import logica.Logica;
import valueObject.VOFlujoCaja;
import valueObject.VOMoneda;

public class FlujoDeCaja extends CustomComponent implements View {

	@AutoGenerated
	private VerticalLayout mainLayout;
	private HorizontalLayout firstRow;
	private PopupDateField date;
	private Label lblTitle;
	private ComboBox cboMoneda;
	private Grid grdFlujo;
	private BeanItemContainer<VOFlujoCaja> ds;	
	private Logica logica;
	private Label lblMessage;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public FlujoDeCaja() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		logica = new Logica();
		
		
		date.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub		
				getFlujoDeCaja();					
			}
		});
		
		cboMoneda.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub
				getFlujoDeCaja();					
			}
		});
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();	
		mainLayout.setSpacing(true);		
		mainLayout.setImmediate(true);
		mainLayout.setWidth("100%");
		mainLayout.setDefaultComponentAlignment(Alignment.TOP_CENTER);
		
		lblTitle = new Label("Flujo de caja");
		lblTitle.setSizeUndefined();
		lblTitle.setStyleName("h2");
		mainLayout.addComponent(lblTitle);
		
		firstRow = new HorizontalLayout();	
		firstRow.setSpacing(true);
		firstRow.setImmediate(true);	
		firstRow.addStyleName(ValoTheme.LAYOUT_HORIZONTAL_WRAPPING);
		mainLayout.addComponent(firstRow);		
		
		date = new PopupDateField();				
		date.setCaption("Fecha");
		date.setImmediate(true);		
		firstRow.addComponent(date);
		
		cboMoneda = new ComboBox();
		cboMoneda.setCaption("Moneda");	
		firstRow.addComponent(cboMoneda);
		
		lblMessage = new Label("");
		lblMessage.setStyleName("messageAlert");
		lblMessage.setSizeUndefined();
		mainLayout.addComponent(lblMessage);
		
		grdFlujo = new Grid();		
		grdFlujo.setSizeFull();
		
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		date.setValue(new Date());		
		cargarComboMonedas();
		
		if(grdFlujo != null){
			mainLayout.removeComponent(grdFlujo);		
		}
		lblMessage.setValue("");
		
	}
	
	private void getFlujoDeCaja(){
		//Comprobar que la fecha sea valida y el combo tenga algo seleccionado
		//Obtener el id de la seleccion del combo
		//invocar el metodo flujoDeCaja con la fecha y moneda seleccionada
		//si existe un grid eliminarlo
		//si no es nulo armar el grid y agregarlo al componente
		
		if(grdFlujo != null){
			mainLayout.removeComponent(grdFlujo);			
		}
		
		if(date.isValid() && cboMoneda.getValue() != null){			
			ArrayList<VOFlujoCaja> array =  logica.FlujoDeCaja(date.getValue(), (Integer)cboMoneda.getValue());
			if(array != null && !array.isEmpty()){
				ds = new BeanItemContainer<VOFlujoCaja>(VOFlujoCaja.class, array);
				grdFlujo.removeAllColumns();
				grdFlujo.setContainerDataSource(ds);
				mainLayout.addComponent(grdFlujo);	
				lblMessage.setValue("");
			}else{
				lblMessage.setValue("No hay registros para mostrar");
			}
		}		
	}
	
	private void cargarComboMonedas(){
		cboMoneda.clear();	
		
		for (VOMoneda moneda : logica.ObtenerMonedas()) {
			cboMoneda.addItem(moneda.getId());
			cboMoneda.setItemCaption(moneda.getId(), moneda.getSimbolo());			
		}	
		
	}

}
