package grafica;

import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import datos.Datos;
import logica.Logica;

public class TotalEnCaja extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	
	@AutoGenerated
	private Label lblTitle;
	private Label lblMessage;
	private PopupDateField date;	
	private TextField txtTotal;
	
	/**
	 * The constructor should fi rst build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TotalEnCaja() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		

		// TODO add user code here		
		
		
		date.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub				
				Logica logica = new Logica();
				txtTotal.setConvertedValue(logica.TotalEnCaja(date.getValue()));				
			}
		});
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		
		mainLayout = new VerticalLayout();
		mainLayout.setSpacing(true);		
		mainLayout.setImmediate(true);
		mainLayout.setWidth("100%");
		
		lblTitle = new Label("Total en caja");	
		mainLayout.addComponent(lblTitle);
		
		date = new PopupDateField();		
		date.setCaption("Fecha a consultar");
		mainLayout.addComponent(date);
		
		lblMessage = new Label("");
		lblMessage.addStyleName("messageAlert");
		
		txtTotal = new TextField();	
		txtTotal.setCaption("Total");
		txtTotal.setConverter(Double.class);
		mainLayout.addComponent(txtTotal);
				
		
	
		
		
		return mainLayout;
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub		
		date.setValue(new Date());	
		lblMessage.setValue("");
	}

}
