package grafica;

import java.util.ArrayList;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import datos.Datos;
import logica.Logica;
import valueObject.VOFlujoCaja;
import valueObject.VOTotalEnCajaDesgloce;

public class TotalEnCaja extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	
	@AutoGenerated
	private Label lblTitle;
	private Label lblMessage;
	private PopupDateField date;	
	private TextField txtTotal;
	private Grid grdDesgloce;
	private BeanItemContainer<VOTotalEnCajaDesgloce> ds;
	private Logica logica;
	
	/**
	 * The constructor should fi rst build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TotalEnCaja() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		logica = new Logica();
		

		// TODO add user code here		
		
		
		date.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub		
				
				if(grdDesgloce != null){
					mainLayout.removeComponent(grdDesgloce);
					txtTotal.setConvertedValue(0.00);
				}
				
				if(date.isValid()){
					ArrayList<VOTotalEnCajaDesgloce> array =  logica.TotalEnCajaDesgloce(date.getValue());
					if(array != null && !array.isEmpty()){
						ds = new BeanItemContainer<VOTotalEnCajaDesgloce>(VOTotalEnCajaDesgloce.class, array);						
						grdDesgloce.removeAllColumns();
						grdDesgloce.setContainerDataSource(ds);
						grdDesgloce.setColumnOrder("descripcion", "credito","debito");
						mainLayout.addComponent(grdDesgloce);	
						
						txtTotal.setConvertedValue(logica.TotalEnCaja(date.getValue()));
						
						lblMessage.setValue("");
					}else{
						lblMessage.setValue("No hay registros para mostrar");
					}
				}
			}
		});
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		
		mainLayout = new VerticalLayout();
		mainLayout.setSpacing(true);		
		mainLayout.setImmediate(true);
		mainLayout.setWidth("100%");
		mainLayout.setDefaultComponentAlignment(Alignment.TOP_CENTER);
		
		lblTitle = new Label("Total en caja");	
		lblTitle.setSizeUndefined();
		lblTitle.setStyleName("h2");
		mainLayout.addComponent(lblTitle);
		
		date = new PopupDateField();		
		date.setCaption("Fecha a consultar");
		mainLayout.addComponent(date);
		
		lblMessage = new Label("");
		lblMessage.setSizeUndefined();
		lblMessage.addStyleName("messageAlert");
		mainLayout.addComponent(lblMessage);
		
		txtTotal = new TextField();	
		txtTotal.setCaption("Total");
		txtTotal.setConverter(Double.class);
		mainLayout.addComponent(txtTotal);
		
		grdDesgloce = new Grid();		
		grdDesgloce.setSizeFull();
				
		
		return mainLayout;
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub		
		date.setValue(new Date());		
		if(grdDesgloce != null){
			mainLayout.removeComponent(grdDesgloce);		
		}
		lblMessage.setValue("");
	}

}
